<a href="https://colab.research.google.com/github/navas604/Ciencia-de-Datos-en-Python/blob/main/Tarea%20No.%206%20-%20Ejercicios%20finales%20Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Universidad Galileo**
## **Maestría en Data Science**
## **Ciencia de Datos en Python**
## **Antonio Everardo Navas Contreras, 14003163**
## **14/04/2021**

---

## **Tarea No. 6 - Ejercicios finales Numpy**

---

Importar librerías a utilizar

In [1]:
import numpy as np

## Ejercicios de Notebook **"Clase_07_Numpy_y_linalg-Matrices-parte1.ipynb"**

#### Ejercicio: Diferencia entre np.array y np.matrix

Las matrices de numpy son únicamente bidimensionales, mientras que los arreglos de numpy (ndarrays) con de N dimesiones.

Derivado de ese concepto, las matrices son una subclase de los ndarrays, y por lo tanto heredan todos los atributos y métodos de los ndarrays.

Una de las ventajas mas importantes de las matrices en numpy es que debido a su notación es posible hacer multiplicación de matrices, es un producto matricial.

Los ndarrays son el estándar de vectores, matrices o tensores de numpy. La mayoría de las funciones devuelven como resultado ndarrays y no matrices.

Arreglo de rango 1, con ndarray, el rango va de acuerdo a la forma de los datos ingresados. Un ndarray puede ser de N dimensiones

In [2]:
a = np.array([1, 2, 3])
print(a)
print("Shape: ", a.shape)
print("Rango: ", a.ndim)
print("Tipo:  ", type(a))

[1 2 3]
Shape:  (3,)
Rango:  1
Tipo:   <class 'numpy.ndarray'>


Arreglo de rango 2, con ndarray, el rango va de acuerdo a la forma de los datos ingresados. Un ndarray puede ser de N dimensiones

In [3]:
a = np.array([[1, 2, 3],
              [4,5,6]])
print(a)
print("Shape: ", a.shape)
print("Rango: ", a.ndim)
print("Tipo:  ", type(a))

[[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Rango:  2
Tipo:   <class 'numpy.ndarray'>


Arreglo de rango 3, con ndarray, el rango va de acuerdo a la forma de los datos ingresados. Un ndarray puede ser de N dimensiones

In [4]:
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(a)
print("Shape: ", a.shape)
print("Rango: ", a.ndim)
print("Tipo:  ", type(a))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape:  (2, 2, 2)
Rango:  3
Tipo:   <class 'numpy.ndarray'>


Matriz de rango 2, con matrix, el rango siempre es 2

In [5]:
a = np.matrix([1, 2, 3])
print(a)
print("Shape: ", a.shape)
print("Rango: ", a.ndim)
print("Tipo:  ", type(a))

[[1 2 3]]
Shape:  (1, 3)
Rango:  2
Tipo:   <class 'numpy.matrix'>


Matriz de rango 2, con matrix, el rango siempre es 2

In [6]:
a = np.matrix([[1, 2, 3],
               [4,5,6]])
print(a)
print("Shape: ", a.shape)
print("Rango: ", a.ndim)
print("Tipo:  ", type(a))

[[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Rango:  2
Tipo:   <class 'numpy.matrix'>


## Ejercicios de Notebook **"Clase_08_Numpy_y_linalg-Matrices-parte2.ipynb"**

**Ejercicio aplicado en DS**
Se tiene una red neuronal sencilla(y simplificada) como la de la siguiente imagen:
<img src="https://www.oreilly.com/library/view/practical-convolutional-neural/9781788392303/assets/246151fb-7893-448d-b9bb-7a87b387a24b.png">

Donde:
* INPUT LAYER: un vector X de tamaño = 2 que representa los datos de entrada
* HIDDEN_LAYER :capa oculta con 2 neuronas definidas por los vectores:
    * HL1 = [0.25,0.37]
    * HL2 = [-8,14]
* OUTPUT_LAYER = capa de salida definida por el vector [4,9]

Crear una funcion neural_network(X) para calcular:
* Calcule la salida de cada neurona en la capa intermedia aplicada a la capa de entrada.
* Use el resultado del paso anterior como entrada para la neurona en la capa de salida

Utilizando multiplicación de matrices se debe calcular para cada fila de la matriz de entrada X el valor de las neuronas de la capa intermedia, esto producirá una nueva matriz con el mismo número de filas que X y 2 columnas(1 para cada neurona) , a  los valores de esta matriz se les debe aplicar la función "sigmoid"(descrita a continuación) para limitarlos al intervalo de 0 a 1, esto produce una matriz del mismo tamaño pero con valores entre 0 a 1, esta matriz se multiplica matricialmente por la matriz que representa los pesos de la capa de salida  y este proceso produce un nuevo tensor al cual se debe aplicar nuevamente la función sigmoid. El resultado debe ser un tensor con el mismo número de filas que la matriz X y una sola columna(una predicción para cada fila de X.

<img src="https://cdn-images-1.medium.com/max/1600/1*Xu7B5y9gp0iL5ooBj7LtWw.png">

In [7]:
def sigmoid(x): #convertir los valores de x al rango de 0 a 1
    
    return 1/(1+np.exp(-x))

In [8]:
H1_W = np.array([[0.25,-8],
                 [0.37,14]])

OL_W = np.array([[4],[9]])

X =  np.array([[0.1,0.2],
               [1,2]])

H1 = np.matmul(X,H1_W)
H1 = sigmoid(H1)  # funcion de activacion: convertir a valores en el intervalo de 0 a 1
OL = np.matmul(H1,OL_W)
OL = sigmoid(OL)  # funcion de activacion: convertir a valores en el intervalo de 0 a 1


print(OL)

[[0.99995577]
 [0.99999332]]


Creando la función para red neuronal con 2 neuronas en la capa oculta, con Sigmoid

In [9]:
X =  np.array([[0.1,0.2],
               [1,2]])


def neural_network(X):
  
  H1_W = np.array([[0.25,-8],
                   [0.37,14]])
  
  OL_W = np.array([[4],[9]])


  H1 = np.matmul(X,H1_W)
  H1 = sigmoid(H1)  # funcion de activacion: convertir a valores en el intervalo de 0 a 1
  OL = np.matmul(H1,OL_W)
  OL = sigmoid(OL)  # funcion de activacion: convertir a valores en el intervalo de 0 a 1

  return OL

A = neural_network(X)
print(A)
print(A.shape)

[[0.99995577]
 [0.99999332]]
(2, 1)


### Ejercicio 

Implementar en una funcion neural_network(X) la red neuronal definida por la siguiente arquitectura:

<img src="http://i.imgur.com/UNlffE1.png">

Podemos validar si fue correctamente implementada si usamos como entrada el vector x=[1,1] . Debemos obtener el resultado mostrado en la imagen.

Una vez tenemos la implementacion correcta, cambiar la funcion de activacion de la capa de salida por la funcion de activacion ReLu(https://en.wikipedia.org/wiki/Rectifier_(neural_networks)):

<img src="https://cdn-images-1.medium.com/max/1600/1*DfMRHwxY1gyyDmrIAd-gjQ.png">

Luego evaluar la red neuronal sobre la matriz de datos X(de manera vectorizada):

In [10]:
X = np.array([
    [0.1,2],
    [0.3,0.45],
    [5,9],
    [12,6],
    [7,5],
    [0.3,0.8],
    [12,5],
    [100,200],
    [7,8],
    [300,1500]])

Creando la función para red neuronal con 3 neuronas en la capa oculta, con Sigmoid

In [11]:
X =  np.array([[1,1],
               [1,1]])


def neural_network(X):
  
  H1_W = np.array([[0.712, 0.355, 0.268],
                   [0.112, 0.855, 0.468]])
  
  OL_W = np.array([[0.116], [0.329], [0.708]])


  H1 = np.matmul(X,H1_W)
  H1 = sigmoid(H1)  # funcion de activacion: convertir a valores en el intervalo de 0 a 1
  OL = np.matmul(H1,OL_W)
  OL = sigmoid(OL)  # funcion de activacion: convertir a valores en el intervalo de 0 a 1

  return OL

A = neural_network(X)
print(A)
print(A.shape)

[[0.69269553]
 [0.69269553]]
(2, 1)


Creando la función para red neuronal con 3 neuronas en la capa oculta y Cambiando la función de activación a ReLu

In [12]:
X =  np.array([[1,1],
               [1,1]])


def neural_network(X):
  
  H1_W = np.array([[0.712, 0.355, 0.268],
                   [0.112, 0.855, 0.468]])
  
  OL_W = np.array([[0.116], [0.329], [0.708]])


  H1 = np.matmul(X,H1_W)
  H1 = sigmoid(H1)  # funcion de activacion: convertir a valores en el intervalo de 0 a 1
  OL = np.matmul(H1,OL_W)
  #OL = sigmoid(OL)  # funcion de activacion: convertir a valores en el intervalo de 0 a 1
  OL = np.array(OL)
  OL[OL<0] = 0  

  return OL

A = neural_network(X)
print(A)
print(A.shape)

[[0.81275154]
 [0.81275154]]
(2, 1)


Evaluando la red neuronal sobre la matriz de datos X (de manera vectorizada), con Sigmoid

In [13]:
X = np.array([
    [0.1,2],
    [0.3,0.45],
    [5,9],
    [12,6],
    [7,5],
    [0.3,0.8],
    [12,5],
    [100,200],
    [7,8],
    [300,1500]])


def neural_network(X):
  
  H1_W = np.array([[0.712, 0.355, 0.268],
                   [0.112, 0.855, 0.468]])
  
  OL_W = np.array([[0.116], [0.329], [0.708]])


  H1 = np.matmul(X,H1_W)
  H1 = sigmoid(H1)  # funcion de activacion: convertir a valores en el intervalo de 0 a 1
  OL = np.matmul(H1,OL_W)
  OL = sigmoid(OL)  # funcion de activacion: convertir a valores en el intervalo de 0 a 1

  return OL

A = neural_network(X)
print(A)
print(A.shape)

[[0.70244573]
 [0.66259284]
 [0.75933678]
 [0.75973948]
 [0.75802295]
 [0.6739704 ]
 [0.75954693]
 [0.76005845]
 [0.75952743]
 [0.76005845]]
(10, 1)


Evaluando la red neuronal sobre la matriz de datos X (de manera vectorizada) y Cambiando la función de activación a ReLu

In [14]:
X = np.array([
    [0.1,2],
    [0.3,0.45],
    [5,9],
    [12,6],
    [7,5],
    [0.3,0.8],
    [12,5],
    [100,200],
    [7,8],
    [300,1500]])


def neural_network(X):
  
  H1_W = np.array([[0.712, 0.355, 0.268],
                   [0.112, 0.855, 0.468]])
  
  OL_W = np.array([[0.116], [0.329], [0.708]])


  H1 = np.matmul(X,H1_W)
  H1 = sigmoid(H1)  # funcion de activacion: convertir a valores en el intervalo de 0 a 1
  OL = np.matmul(H1,OL_W)
  #OL = sigmoid(OL)  # funcion de activacion: convertir a valores en el intervalo de 0 a 1
  OL = np.array(OL)
  OL[OL<0] = 0  

  return OL

A = neural_network(X)
print(A)
print(A.shape)

[[0.85897151]
 [0.6748703 ]
 [1.14904686]
 [1.15125178]
 [1.14187076]
 [0.72619803]
 [1.15019715]
 [1.153     ]
 [1.1500904 ]
 [1.153     ]]
(10, 1)
